#!/bin/bash
# This script is not meant to be manually run, as it has to run early in boot!
# Please enable it by running "just hugepages-numa"
# On a system without numa nodes, using kernel arguments will work fine.

# Change the values in /etc/default/hugepages_numa to edit values here
source /etc/default/hugepages_numa
# NODES=(numanode numanode numanode)
# PAGES=how many 1GB pages to reserve per numa node

# Check if numa nodes are even present on the system
nodes_path=/sys/devices/system/node/
if [ ! -d ${nodes_path} ]; then
    echo "ERROR: ${nodes_path} does not exist"
    exit 1
fi

# Function to reserve X 1GB pages on a specified numa node
reserve_pages()
{
    echo "${1}" > "${nodes_path}/node${2}/hugepages/hugepages-1048576kB/nr_hugepages"
    mkdir /dev/hugepages1G
    mount -t hugetlbfs -o pagesize=1G hugetblfs /dev/hugepages1G
}

# Reserve X $PAGES in the $NODES configured
for NODE in "${NODES[@]}"; do
    reserve_pages "${PAGES}" "${NODE}"
done